/**
 * GuSprites Boriel Basic Exporter
 * Converts ZX Spectrum pixel/attribute data into Boriel Basic code blocks using GuSprites format.
 * Format: Columns of 8 pixels wide, scanning from top to bottom (y=0 to w-1).
 */

window.ZXExportGuSprites = function(pixels, attributes, imgWidth, imgHeight, w, rows, cols, name, matrix, noAttrs) {
    const total_bytes = (w / 8) * (w / 8) * 8;
    const total_sprites = rows * cols;
    const attr_bytes_per_sprite = (w / 8) * (w / 8);
    
    const extractSprite = (r, c) => {
        let sprite = [];
        let startCol = c * w;
        let startRow = r * w;
        for (let y = 0; y < w; y++) {
            let rowData = [];
            for (let x = 0; x < w; x++) {
                const py = startRow + y;
                const px = startCol + x;
                if (py < imgHeight && px < imgWidth) {
                    rowData.push(pixels[py * imgWidth + px]);
                } else {
                    rowData.push(0);
                }
            }
            sprite.push(rowData);
        }
        return sprite;
    };

    const extractSpriteAttributes = (r, c) => {
        let attrData = [];
        let spriteBlocks = w / 8;
        let totalBlocksWidth = imgWidth / 8;
        let startBlockCol = c * spriteBlocks;
        let startBlockRow = r * spriteBlocks;
        
        for (let br = 0; br < spriteBlocks; br++) {
            for (let bc = 0; bc < spriteBlocks; bc++) {
                const blockIndex = (startBlockRow + br) * totalBlocksWidth + (startBlockCol + bc);
                if (blockIndex < attributes.length) {
                    attrData.push(attributes[blockIndex]);
                } else {
                    attrData.push(0);
                }
            }
        }
        return attrData;
    };

    // GuSprites format: 8-pixel wide vertical columns
    const bitmapToBytes = (sprite) => {
        let bytesData = [];
        let charsPerCol = w / 8;
        for (let colBlock = 0; colBlock < charsPerCol; colBlock++) {
            for (let y = 0; y < w; y++) {
                let byteVal = 0;
                for (let xOffset = 0; xOffset < 8; xOffset++) {
                    let x = colBlock * 8 + xOffset;
                    if (sprite[y][x]) {
                        byteVal |= (1 << (7 - xOffset));
                    }
                }
                bytesData.push(byteVal);
            }
        }
        return bytesData;
    };

    const formatBytes = (bytesData) => {
        let hexStrings = bytesData.map(b => '$' + b.toString(16).toUpperCase().padStart(2, '0'));
        let lines = [];
        for (let i = 0; i < hexStrings.length; i += 8) {
            let line = hexStrings.slice(i, i + 8).join(',');
            if (i + 8 < hexStrings.length) line += ',';
            lines.push(line);
        }
        return lines.join(' _\n\t');
    };

    const formatBytesInline = (bytesData) => {
        return bytesData.map(b => '$' + b.toString(16).toUpperCase().padStart(2, '0')).join(',');
    };

    let out = [];
    out.push(`' Generated by ZXDraw - GuSprites Format`);
    out.push(`' Size: ${w}x${w}`);
    out.push(`' Count: ${total_sprites}\n`);

    if (matrix) {
        let flatTiles = [];
        let flatAttrs = [];
        for (let r = 0; r < rows; r++) {
            for (let c = 0; c < cols; c++) {
                let sprite = extractSprite(r, c);
                flatTiles.push(bitmapToBytes(sprite));
                if (!noAttrs) flatAttrs.push(extractSpriteAttributes(r, c));
            }
        }

        out.push(`' ${name} matrix: ${total_sprites} x ${total_bytes}`);
        out.push(`Dim ${name}(${total_sprites - 1},${total_bytes - 1}) As Ubyte => { _`);
        for (let i = 0; i < flatTiles.length; i++) {
            let formatted = formatBytes(flatTiles[i]).replace(/\n\t/g, '\n\t\t');
            let end = (i < flatTiles.length - 1) ? ', _' : ' _';
            out.push(`\t{ _\n\t\t${formatted} _\n\t}${end}`);
        }
        out.push(`}\n`);

        if (!noAttrs) {
            out.push(`' Attributes matrix: ${total_sprites} x ${attr_bytes_per_sprite}`);
            out.push(`Dim ${name}Attr(${total_sprites - 1},${attr_bytes_per_sprite - 1}) As Ubyte => { _`);
            for (let i = 0; i < flatAttrs.length; i++) {
                let inline = formatBytesInline(flatAttrs[i]);
                let end = (i < flatAttrs.length - 1) ? ', _' : ' _';
                out.push(`\t{ ${inline} }${end}`);
            }
            out.push(`}\n`);
        }
    } else {
        let count = 0;
        for (let r = 0; r < rows; r++) {
            for (let c = 0; c < cols; c++) {
                let sprite = extractSprite(r, c);
                let bytesData = bitmapToBytes(sprite);
                let formattedData = formatBytes(bytesData);
                out.push(`Dim ${name}${count}(${total_bytes - 1}) As Ubyte => { _\n\t${formattedData} _\n}`);
                
                if (!noAttrs) {
                    let attrData = extractSpriteAttributes(r, c);
                    let formattedAttr = formatBytesInline(attrData);
                    out.push(`Dim ${name}Attr${count}(${attr_bytes_per_sprite - 1}) As Ubyte => { ${formattedAttr} }`);
                }
                out.push('');
                count++;
            }
        }
    }

    return out.join('\n');
};
