/**
 * Boriel Basic (.bas) Importer
 * Reverses the ZXDrawer PutChars matrix export format back into pixel/attribute data.
 *
 * Supports the matrix format generated by ZXExportPutChars:
 *   Dim name(count-1, totalBytes-1) As Ubyte => { { $XX,... }, ... }
 *   Dim nameAttr(count-1, attrBytes-1) As Ubyte => { { $XX,... }, ... }
 */

/**
 * Parse a Boriel Basic matrix .bas file.
 * Returns { pixels, attributes, canvasWidth, canvasHeight } ready to be placed
 * on a ZXDrawer canvas, or null on parse failure.
 *
 * @param {string} text      - Raw .bas file content
 * @param {number} tileW     - Tile width in pixels (e.g. 8, 16, 24...)
 * @param {number} cols      - Number of tile columns in the source canvas
 * @param {number} rows      - Number of tile rows in the source canvas
 */
function parseBas(text, tileW, cols, rows) {
    const totalSprites = cols * rows;
    const tileH = tileW; // PutChars tiles are always square (w x w)
    const charsPerTile = tileW / 8; // blocks per tile side
    const bytesPerTile = charsPerTile * charsPerTile * 8; // = total_bytes in exporter

    // ── 1. Extract all hex byte groups from Dim declarations ─────────────────
    // We find each { ... } group inside a Dim block and collect the $XX values.
    const extractDimGroups = (dimText) => {
        const groups = [];
        // Match each { ... } group (may span multiple lines with _ continuations)
        const groupRe = /\{([^}]*)\}/g;
        let m;
        while ((m = groupRe.exec(dimText)) !== null) {
            const bytes = [];
            const byteRe = /\$([0-9A-Fa-f]{2})/g;
            let bm;
            while ((bm = byteRe.exec(m[1])) !== null) {
                bytes.push(parseInt(bm[1], 16));
            }
            if (bytes.length > 0) groups.push(bytes);
        }
        return groups;
    };

    // ── 2. Find the two Dim blocks ────────────────────────────────────────────
    // Normalise line continuations so we can regex across lines easily.
    const flat = text.replace(/\s*_\s*\n\s*/g, ' ');

    // Graphics Dim: name(count-1, bytesPerTile-1)
    const gfxRe = /Dim\s+\w+\s*\(\s*\d+\s*,\s*\d+\s*\)\s*As\s+Ubyte\s*=>\s*\{([\s\S]*?)\}\s*(?=Dim|\s*$)/i;
    // We need the FIRST Dim (gfx) and the SECOND (attr). Split on "Dim" tokens.
    const dimMatches = [...text.matchAll(/Dim\s+\w+[\s\S]*?(?=\nDim\s|\n'\s|\s*$)/gi)];

    // Separate gfx vs attr dims by name suffix
    let gfxBlock = null, attrBlock = null;
    for (const dm of dimMatches) {
        const header = dm[0].match(/Dim\s+(\w+)\s*\(/i);
        if (!header) continue;
        const varName = header[1];
        if (/Attr/i.test(varName)) {
            attrBlock = dm[0];
        } else {
            gfxBlock = dm[0];
        }
    }

    if (!gfxBlock) return null;

    const tileGroups = extractDimGroups(gfxBlock);
    const attrGroups = attrBlock ? extractDimGroups(attrBlock) : [];

    if (tileGroups.length < totalSprites) {
        console.warn(`parseBas: expected ${totalSprites} tiles, found ${tileGroups.length}`);
        return null;
    }

    // ── 3. Reconstruct pixel canvas ──────────────────────────────────────────
    const canvasW = cols * tileW;
    const canvasH = rows * tileH;
    const pixels = new Uint8Array(canvasW * canvasH);
    const attributes = new Uint8Array((canvasW / 8) * (canvasH / 8));

    for (let spriteIdx = 0; spriteIdx < totalSprites; spriteIdx++) {
        const r = Math.floor(spriteIdx / cols);
        const c = spriteIdx % cols;
        const spriteBytes = tileGroups[spriteIdx];

        // bitmapToBytes in exporter iterates: colBlock → rowBlock → yOffset
        // We reverse: for each byte, derive (colBlock, rowBlock, yOffset) → (x, y)
        let byteIdx = 0;
        for (let colBlock = 0; colBlock < charsPerTile; colBlock++) {
            for (let rowBlock = 0; rowBlock < charsPerTile; rowBlock++) {
                for (let yOffset = 0; yOffset < 8; yOffset++) {
                    const byteVal = spriteBytes[byteIdx++] || 0;
                    const localY = rowBlock * 8 + yOffset;
                    const localX = colBlock * 8;
                    for (let bit = 0; bit < 8; bit++) {
                        const px = c * tileW + localX + bit;
                        const py = r * tileH + localY;
                        pixels[py * canvasW + px] = (byteVal >> (7 - bit)) & 1;
                    }
                }
            }
        }

        // Attributes: charsPerTile × charsPerTile blocks per sprite
        const attrData = attrGroups[spriteIdx] || [];
        const totalBlocksW = canvasW / 8;
        const startBlockCol = c * charsPerTile;
        const startBlockRow = r * charsPerTile;
        let ai = 0;
        for (let br = 0; br < charsPerTile; br++) {
            for (let bc = 0; bc < charsPerTile; bc++) {
                const blockIdx = (startBlockRow + br) * totalBlocksW + (startBlockCol + bc);
                attributes[blockIdx] = attrData[ai++] !== undefined ? attrData[ai - 1] : 0x07;
            }
        }
    }

    return { pixels, attributes, canvasWidth: canvasW, canvasHeight: canvasH };
}

// Expose globally for renderer.js
window.ZXImportBas = parseBas;
